### PR TITLE
Bridge_common : Unit testing added for bridge_common

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: root <root@dhcp41-162.lab.eng.blr.redhat.com>

### CODE REVIEW

**Comment by r0h4n** [comment]
@GowthamShanmugam could you add more unit tests to coverage the missing files as per https://coveralls.io/builds/8088336

**Comment by r0h4n** [comment]
@shtripat @nthomas-redhat please review

**Comment by shtripat** [comment]
Looks fine to me. +1

**Comment by r0h4n** [comment]
Please resolve merge conflicts and resend  patch

**Comment by r0h4n** [comment]
Thanks for the review @nthomas-redhat , Good to see such coverage @GowthamShanmugam

**Pull request merged**
